name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 👈 Required for semantic-release to see tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          pip install python-semantic-release

      - name: Run semantic-release version
        run: |
          python -m semantic_release version  # This bumps the version

      - name: Run semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This will automatically use the GitHub token for authentication
        run: |
          python -m semantic_release publish  # This pushes the version and tags
